//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutabakatOtomasyon.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HedefDepoOrhanlıDepo
    {
        public int ID { get; set; }
        public string AdresAdi { get; set; }
        public string Il { get; set; }
        public string ÇEKİCİ { get; set; }
        public string KIRKAYAK { get; set; }
        public string ONTEKER { get; set; }
    }
}
