//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MutabakatOtomasyon.entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbMutabakatEntities3 : DbContext
    {
        public DbMutabakatEntities3()
            : base("name=DbMutabakatEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HedefDepoOrhanlıDepo> HedefDepoOrhanlıDepo { get; set; }
        public virtual DbSet<TblHedefEskiFiyatBilgileri> TblHedefEskiFiyatBilgileri { get; set; }
        public virtual DbSet<SudesanFiyatListesi> SudesanFiyatListesi { get; set; }
    }
}
